### ISSUE TITLE
Warning when entering space in any of yasnippet fields

### ISSUE THREAD

**Issue by CSRaghunandan** [joaotavora/yasnippet#794] opened 2017-03-29 07:40 UTC
one of the latest commit seems to have broken yasnippet-mode for me. I'm using emacs master build and whenever I enter a space in any fields(like the function arguments, etc.) I get an warning message and yasnippet stops working.

warning message:
```
Warning (yasnippet): Couldn’t find: "[[:space:]
]*const[[:space:]
]*init[[:space:]
]*=[[:space:]
]*require(\"\\./passport\");[[:space:]
]*init();[[:space:]
]*function(asdf[[:space:]
]*)[[:space:]
]*{[[:space:]
]*}[[:space:]
]*\\(\\)[[:space:]
]*}"
```

Any idea why this is happening?

I've reverted to using the older version of yasnippet and everything seems to be fine there.

**Comment by npostavs** [comment] 2017-03-29 13:19
Sounds like a bug caused by #789. Can you show how to reproduce this starting from `emacs -Q`?

**Comment by CSRaghunandan** [comment] 2017-03-29 20:03
@npostavs  I'm unable to reproduce the bug in `emacs -Q`. I thought the issue was the configuration for yasnippet in my `.emacs.d`, turns it wasn't it the cause. I uncommented all of my yasnippet related config and ran emacs with my config and manually enabled `yas-minor-mode` and I still get the same problem :(

**Comment by npostavs** [comment] 2017-03-29 20:08
It's probably related to some non-yasnippet config. `auto-fill-mode` is probably important, and possibly some other things (I've tried with yasnippet+auto-fill, but it didn't happen for me).

**Comment by CSRaghunandan** [comment] 2017-03-29 20:21
Agh, I disabled `auto-fill-mode` and now yasnippets works without any problems O_O
I added this to my emacs config: 
``` elisp
(add-hook 'snippet-mode-hook '(lambda ()
                                  (auto-fill-mode -1)))
```
but that didn't solve the problem. Maybe this is a problem with emacs master build. Any workarounds for this problem other than switching off `auto-fill-mode` ?

**Comment by npostavs** [comment] 2017-03-29 20:29
I think `(advice-add 'yas--auto-fill-wrapper :override #'ignore)` should make it work for now, but I'd like to figure out exactly what triggers this so I can fix it properly.

**Comment by npostavs** [comment] 2017-04-02 04:07
I tried installing your .emacs.d from https://github.com/CSRaghunandan/.emacs.d, and doing `(advice-remove 'yas--auto-fill-wrapper #'ignore)` but I didn't get the error. Is there a particular snippet and/or mode that triggers it?

**Comment by CSRaghunandan** [comment] 2017-04-02 06:34
I added `(advice-remove 'yas--auto-fill-wrapper #'ignore)` in my `.emacs.d` and that seems to have fixed the error when typing a space in yasnippet 👍

**Comment by npostavs** [comment] 2017-04-02 12:17
> I added `(advice-remove 'yas--auto-fill-wrapper #'ignore)` in my .emacs.d and that seems to have fixed the error when typing a space in yasnippet

What? Now I'm confused. That just disables the workaround I suggested earlier.

If you don't put any advice on yasnippet, can you trigger this bug?  And if so, which snippet triggers it?

**Comment by CSRaghunandan** [comment] 2017-04-02 17:29
I'm really sorry, I got very confused with something and wrote a stupid comment.

heres what I did: from my latest commit in my [.emacs.d](https://github.com/CSRaghunandan/.emacs.d), I evaluated `(advice-remove 'yas--auto-fill-wrapper #'ignore)`. After that, I'm not getting errors when entering space in yasnippet snippet-mode.

But, If I remove `(advice-add 'yas--auto-fill-wrapper :override #'ignore)` from my emacs.d, and restart emacs, I get errors again when entering space while in snippet-mode

**Comment by npostavs** [comment] 2017-04-02 17:36
> I get errors again when entering space while in snippet-mode

Can you explain exactly what you mean this? Is that while writing a new snippet? Or while tabbing through the fields of a snippet? Which snippet?

**Comment by CSRaghunandan** [comment] 2017-04-02 18:25
> Can you explain exactly what you mean this? Is that while writing a new snippet? Or while tabbing through the fields of a snippet? Which snippet?

This happens when expanding snippets like `if` or `function` or `for`, when I'm inside the parenthesis to type function arguments or the if condition and I type a space anywhere inside, yasnippets throws out a warning(which i mentioned in OP) and stops working.

**Comment by npostavs** [comment] 2017-04-02 18:28
> This happens when expanding snippets like `if` or `function` or `for`

Which major mode is this in? Javascript?

**Comment by npostavs** [comment] 2017-04-02 19:20
Ok, I got it, simplest reproducer: `emacs -Q -l yasnippet -f yas-global-mode -f js-mode -f auto-fill-mode` insert `f`, press <kbd>tab</kbd> to expand the `function` snippet, then hit <kbd>space</kbd> in the first field.

**Comment by npostavs** [comment] 2017-04-04 01:15
Should be fixed by #798.

**Closed** 2017-04-08 23:09 UTC
Labels: bug

**Comment by shackra** [comment] 2019-10-24 20:56
I'm experienced this bug right now

it was right after [creating these snippets](https://gitlab.com/shackra/emacs/commit/749c94fdc861615fcd11a10b030d094195e15e64)

The commit of the package is d91dd66f2aed9bbaef32813a68b105ea77e83890 (I use straight.el for managing my packages)

**Comment by npostavs** [comment] 2019-12-13 21:17
@shackra could you open a new bug with details please?
