### ISSUE TITLE
Any snippet using python-args-to-docstring returns Wrong type argument: listp

### ISSUE THREAD

**Issue by RidaAyed** [joaotavora/yasnippet#1200] opened 2024-07-26 11:50 UTC
Expanding e.g. `function_docstring` and tabbing the cursor to args,  shows `error Wrong type argument: listp`  written into the docstr upon typing. Instead of the args I'm typing.

#### System Info :computer:
- OS: gnu/linux
- Emacs: 29.4
- Spacemacs: 0.999.0
- Spacemacs branch: develop (rev. 20a8c6b43)
- Graphic display: t
- Running in daemon: nil
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((spacemacs-layouts :variables spacemacs-layouts-restrict-spc-tab t)
 systemd graphviz
 (spell-checking :variables spell-checking-enable-by-default nil spell-checking-enable-auto-dictionary t enable-flyspell-auto-completion t)
 yaml
 (json :variables json-fmt-tool 'web-beautify)
 latex pass csv prodigy
 (treemacs :variables treemacs-use-all-the-icons-theme t)
 search-engine
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-sort-by-usage t auto-completion-idle-delay 0.2 auto-completion-minimum-prefix-length 2)
 exwm emacs-lisp git helm finance
 (org :variables org-enable-hugo-support t org-enable-github-support t)
 (shell :variables shell-default-shell 'ansi-term shell-default-height 30 shell-default-position 'right spacemacs-vterm-history-file-location "~/.bash_history")
 (version-control :packages
                  (not git-gutter))
 mu4e pdf
 (python :variables python-backend 'lsp python-lsp-server 'pyright python-test-runner 'pytest))
```
- System configuration features: ACL CAIRO DBUS FREETYPE GIF GLIB GMP GNUTLS GPM GSETTINGS HARFBUZZ JPEG JSON LCMS2 LIBOTF LIBSYSTEMD LIBXML2 M17N_FLT MODULES NOTIFY INOTIFY PDUMPER PNG RSVG SECCOMP SOUND SQLITE3 THREADS TIFF TOOLKIT_SCROLL_BARS TREE_SITTER WEBP X11 XDBE XIM XINPUT2 XPM GTK3 ZLIB

**Comment by quazgar** [comment] 2024-10-17 08:17
I can reproduce this with plain Emacs:

```py
def fd(foo):
    """
    Wrong type argument: listp, "foo"
    """

def fdn(bar):
    """

    Wrong type argument: listp, "bar"
    """ 
```

- GNU Emacs 29.4 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0) of 2024-07-22, modified by Debian
- yasnippet: 20241013.1557
- yasnippet-snippets: 20241014.949

**Comment by monnier** [comment] 2024-10-22 00:03
> I can reproduce this with plain Emacs:

Neither Emacs nor YAsnippet refer to or define
`python-args-to-docstring`, so this looks like a problem in
`yasnippet-snippets` rather than in YAsnippet (and AFAICT there's
already an issue open for that over there).

Am I missing something?

**Comment by quazgar** [comment] 2024-10-22 08:06
> so this looks like a problem in `yasnippet-snippets`

Exactly, that's why I opened [#505 there](https://github.com/AndreaCrotti/yasnippet-snippets/issues/505#issue-2593997652). I am fine with closing this issue. Can Github semantically link to that other issue and tell people straightforward to look there?

**Comment by monnier** [comment] 2024-10-23 14:11
I think your message does just that :smiley:, thanks.

**Closed by monnier** 2024-10-23 14:11 UTC
