### ISSUE TITLE
Same trigger key strange behavior

### ISSUE THREAD

**Issue by Ynjxsjmh** [joaotavora/yasnippet#994] opened 2019-04-22 06:40 UTC
I want to quickly input [Symbols in Org-mode](https://orgmode.org/worg/org-symbols.html), say input `a` and then TAB for `&alpha;` in markdown mode. 

Since I also use the [yasnippet-snippets](https://github.com/joaotavora/yasnippet) package whose path is `~\.emacs.d\elpa\yasnippet-snippets-0.7\snippets`. So I place my own snippets in `~\.emacs.d\snippets`.

Because I want to use snippets in markdown mode, so I create a subdir named `markdown-mode` in `~\.emacs.d\snippets`. Then I add a file named `math-sub` in this subdir. It goes like `~\.emacs.d\snippets\markdown-mode\math-sub` now.

What `math-sub` contains:
```
# -*- mode: snippet -*-
# name: math-sub
# key: _
# --

<sub>$1</sub>$2
```

But I find there is a file named [emphasis](https://github.com/AndreaCrotti/yasnippet-snippets/blob/master/snippets/markdown-mode/emphasis) in ` yasnippet-snippets` whose short key is `_` too.

So every time I input `_` and TAB I will get a popup prompts me to choose a snippet. If I input `1` it will produce `<sub>$1</sub>$2`. If I input 2, it will produce `_${1:Text}_ $0`.

![image](https://user-images.githubusercontent.com/40143136/56486702-1f8eab00-650b-11e9-8373-fea6e26f5e5d.png)

That's the feature I want.

Since there are some greek alphabets which have the same prefix, such as `eta` and `epsilon`. I use the same trigger key `e` for them. 

But after I do that and reload all my snippets, I input `e` and TAB wouldn't expand it or give me a popup.

So is there any way for me to get the same feature as I described first?

**Comment by npostavs** [comment] 2019-04-22 12:11
> Since there are some greek alphabets which have the same prefix, such as `eta` and `epsilon`. I use the same trigger key `e` for them.
> 
> But after I do that and reload all my snippets, I input `e` and TAB wouldn't expand it or give me a popup.

This should work. Can you show the contents of those snippet files, and where did you put the files?

**Comment by Ynjxsjmh** [comment] 2019-04-22 13:29
That's really strange, I just tried it once more, it works for me then. But I'm sure when I submitted the issue, this problem existed. And I remember I would have got the error `Cannot open load file: No such file or directory, dropdown-list` sometimes.

**Comment by npostavs** [comment] 2019-04-22 13:33
It sounds like you may have installed `dropdown-list` incorrectly.

**Comment by Ynjxsjmh** [comment] 2019-04-22 14:23
I have no idea, I use the configuration based on [redguardtoo/emacs.d](https://github.com/redguardtoo/emacs.d). And I use grep to find out `dropdown-list` is in `site-lisp` dir. What he introduces `site-lisp` is:

> # Locked packages
> Some packages are so important to my workflow that they are locked.
> Those packages are placed at `~/.emacs.d/site-lisp`.
> They will not be upgraded by `ELPA.emacs.d/site-lisp` at first.

And he has done all the configuration include yasnippet and dropdown-list.

I remembered that in the morning, I changed the file organization.

From
```
~\.emacs.d\snippets>tree markdown-mode /f
├─markdown-mode
│      greek-alphabet-alpha
│      greek-alphabet-beta
│      HTML-vertical-line
│      math-sub
│      math-sup
```
To
```
~\.emacs.d\snippets>tree markdown-mode /f
│  .yas-make-groups
│
├─greek-alphabet
│      epsilon
│      eta
│      nu
│      omega
│      omicron
│
├─HTML-symbol
│      center
│
├─math
│      cup
│
└─symbol
        symbol-prime
        symbol-vertical-line
```

And before I changed the file organization, the is no same trigger key. When I adjusted the file organization, I added the remaining greek alphabets(here introduces the same trigger key). And then I used `yas-reload-all` to reload all the yasnippets.

After that, I got the problem `Cannot open load file: No such file or directory, dropdown-list`. And I cleared folder `markdown-mode` and did some simple test on same trigger key, but don't work(the situation I described in this issue).

I used `yas-reload-all` every time I made some changes (I don't remember whether I have restarted my Emacs once). Maybe I think I need to restart Emacs at my case? Because I restarted my Emacs to if the problem I met in issue 612  is solved. And then found out the problem I met in the morning disappeared.

**Comment by npostavs** [comment] 2019-04-22 14:44
> I use the configuration based on [redguardtoo/emacs.d](https://github.com/redguardtoo/emacs.d).

Seems like it should work. I see it autoloads `dropdown-list` here: https://github.com/redguardtoo/emacs.d/blob/becb84b6185c51a55b4fa5beadba2bfb6330c7f9/lisp/init-autoload.el#L56, so if the `dropdown-list.el` file is not in one of the directories of `load-path` you could that error. It looks like https://github.com/redguardtoo/emacs.d/blob/becb84b6185c51a55b4fa5beadba2bfb6330c7f9/lisp/init-site-lisp.el does add it the `load-path`, so I can't see why it shouldn't work, unless while moving folders around, you accidentally also moved `dropdown-list.el`?

Anyway, as far as I can tell, this is not a bug in yasnippet, so I will close it.

**Closed by npostavs** 2019-04-22 14:44 UTC
