### ISSUE TITLE
Rust mode - yasnippet disables smartparents

### ISSUE THREAD

**Issue by CajetanP** [joaotavora/yasnippet#801] opened 2017-04-06 18:36 UTC
Hey, I noticed a bug regarding smartparents.
Expanding snippets disables smartparents, but usually it gets reenabled as soon as I finish editing the expanded snippet, however not all the time.
Particularly, when I expand the snippet "println", I use tab to jump to arguments and then I press escape to leave. Smartparents stays disabled which is *very* annoying because I have to enable it again after each snippet.

**Comment by npostavs** [comment] 2017-04-06 18:41
Hmm, possibly related to #785? Do you use `hippie-expand`?

> Particularly, when I expand the snippet "println",

What's the full definition of the `println` snippet?

**Comment by CajetanP** [comment] 2017-04-06 18:51
Result is the same no matter if I expand with hippie-expand or with standard yas expand.

Here's the full definition of _println_:
```
# -*- mode: snippet -*-
# name: println!("{}", value);
# key: println
# --
println!("${1:{}}", $2);
```

**Comment by npostavs** [comment] 2017-04-06 19:15
I can't reproduce this. I tried `emacs -Q -L . -l yasnippet -f yas-global-mode -L ../dash -L ../rust-mode -l rust-mode -L ../smartparens -l smartparens -f smartparens-global-mode -f rust-mode` entered `printf` hit `<tab>`, smartparens mode was not disabled, that is, pressing `(` entered a closing `)` in both fields, and after exiting.

Emacs version 24.5, yasnippet 5043a961215158619199cf03a85a0c063a28c644, rust-mode rust-lang/rust-mode@0de149a9ad04f652cd7a59a9ef67be8a7d86ba76, smartparens Fuco1/smartparens@0c81107de550931466b11132b8c6286851615b5f

**Comment by npostavs** [comment] 2017-04-21 16:58
I'm closing as there doesn't seem to be a reproducible bug here.

**Closed by npostavs** 2017-04-21 16:58 UTC
Labels: cannot reproduce, need clarification
