### ISSUE TITLE
Overide the snippet of the parent mode?

### ISSUE THREAD

**Issue by netjune** [joaotavora/yasnippet#1024] opened 2019-10-30 01:52 UTC
I think it is safe to overide the snippet of the parent mode, which has the same name and key. But it doesn't. When expanding the snippet, it prompts for the snippet to expand and there is only one item in the candidate buffer.

And the overiding can even be applied to snippets which only have the same key. Can you provide an option to control this?

**Comment by npostavs** [comment] 2019-12-13 19:52
Duplicate of #270

**Comment by npostavs** [comment] 2019-12-13 19:52
See also https://github.com/joaotavora/yasnippet/issues/917#issuecomment-372660806

**Closed by npostavs** 2019-12-13 19:52 UTC
