### ISSUE TITLE
Automatically generate a local snippet for functions defined in current buffer

### ISSUE THREAD

**Issue by veronikazaglotova** [joaotavora/yasnippet#1084] opened 2020-12-04 09:40 UTC
For example, in Python I have a function `getletters(lst,n)`. I want yasnippet to automatically generate a snippet for that function, so that when I type `getl` and complete it with Company, yasnippet triggers itself and moves the cursor to "lst" where I type a list name, then when I press TAB it moves the cursor to n where I type a number, then when I press TAB again it moves the cursor after the closing bracket.
This also has to only work in the current buffer, not in other buffers where this function isn't there.
I also think that it should work for functions imported from libraries and for functions that are imported from other files.
Is this possible, and if it is, how?
Does this exist in other IDEs? I only used Emacs to this point.

**Comment by joaotavora** [comment] 2020-12-14 17:37
Check out the Eglot project, it a modern "language server" to understand what is a function in your code and offer a completion. Some of those completions eventually expand into dynamically generated snippets, much like you describe.  I think your use case is covered there, and I don't have plans to add this to yasnippet.  So closing this, but feel free to continue the discussion.

**Closed by joaotavora** 2020-12-14 17:37 UTC

**Comment by veronikazaglotova** [comment] 2020-12-14 20:37
Sad! Ok, I'll use Eglot or lsp-mode then.
If I contributed that feature to yasnippet, would you accept the patch, or would you consider it additional unneeded bloat?

**Comment by joaotavora** [comment] 2020-12-14 22:39
> If I contributed that feature to yasnippet, would you accept the patch, or would you consider it additional unneeded bloat?

Depends on how you contributed it, i.e. how you design it. 

Here are two questions:

- How would yasnippet collect the information about functions avalable to call locally?  
- When would this information be collected? 

I think you'll find that making yasnippet do this is quite complex.  It's better to have another program that is specialized in these tasks (finding functions that you can call at any given position in a buffer) perform these tasks.  Such a program is Eglot or lsp-mode.

**Comment by joaotavora** [comment] 2020-12-14 22:39
But you may have some fundamental insight that I'm missing, of course, so feel free to explain.

**Comment by veronikazaglotova** [comment] 2020-12-14 22:47
> * How would yasnippet collect the information about functions avalable to call locally?

IDK. Regex on a region, maybe? I'm not a programmer...
If regex won't work out, every time a snippet is expanded we can write that somewhere in RAM, but it's too bloated.
Perhaps we can copy that from LSP source code? It's probably a big project though
>When would this information be collected?
That's a hard question :/

**Comment by veronikazaglotova** [comment] 2020-12-14 22:54
Emacs is distributed with ElDoc. It shows function arg list when under the modeline. Maybe that will help IDK, I'll read the source code later
Here's a pic of ElDoc in practice:
![Screenshot_20201215-045149_Termux](https://user-images.githubusercontent.com/52463107/102145445-6a53f800-3e91-11eb-9bea-15394318b892.jpg)

**Comment by joaotavora** [comment] 2020-12-14 22:57
Actually the first question is harder, in my opinion.

I'm a programmer. A good very generic approach to hard stuff is: "divide and conquer". In other words, let tools specialize in doing one thing, and doing it well. Also know as https://en.wikipedia.org/wiki/Unix_philosophy.  So in this case yasnippet specializes in expanding snippets, other tools specialize in discovering what functions are available.  Let these tools play together with yasnippet.

And, yes I know about ElDoc.  I help maintain it in Emacs :-) 

ElDoc only knows about Elisp function, it doesn't know about functions in other languages like Python.  *Unless* you connect a tool like Eglot.  It's the very same problem again.  Let each thing do its thing.  The problem is you are trying to solve is likely *already* solved.  (Maybe you can improve the solution, who knows).

**Comment by joaotavora** [comment] 2020-12-14 22:58
I'd love to help you pursue your Emacs hacks, but I don't have time.  I recommend you subscribe to the Emacs-devel mailing list. https://en.wikipedia.org/wiki/Unix_philosophy

**Comment by veronikazaglotova** [comment] 2020-12-14 23:00
Thanks
Good night, joaotavora
