### ISSUE TITLE
Bad update

### ISSUE THREAD

**Issue by johncming** [joaotavora/yasnippet#888] opened 2018-01-10 03:42 UTC
The snippets were not loaded automatically. 

I must set up a fixed directory. I use only a small fraction of snippets.

**Comment by npostavs** [comment] 2018-01-10 03:45
See [the README](https://github.com/joaotavora/yasnippet#where-are-the-snippets):

> # Where are the snippets?
> 
> Yasnippet no longer bundles snippets directly, but it's very easy to
> get some!
> 
> 1. [yasnippet-snippets](http://github.com/AndreaCrotti/yasnippet-snippets) - a snippet collection package maintained by
>     [AndreaCrotti](https://github.com/AndreaCrotti).
> 
>     It can be installed with `M-x install-package RET
>     yasnippet-snippets` if you have added MELPA to your package
>     sources.

**Comment by johncming** [comment] 2018-01-10 03:50
worked, thank you

**Comment by npostavs** [comment] 2018-01-10 03:53
Duplicate of #885

**Closed** 2018-01-10 03:53 UTC
Labels: support
