### ISSUE TITLE
org src block yas-expand error post-command-hook wrong number of arguments

### ISSUE THREAD

**Issue by dericbytes** [joaotavora/yasnippet#976] opened 2019-01-13 10:20 UTC
I am setting up an elisp snippet to expand in an org source block

emacs -q
```(add-to-list 'load-path "~/.emacs.d/el-get/yasnippet")
(setq yas-snippet-dirs '("~/tmp/snippets"))
(require 'yasnippet)
(yas-global-mode 1)
(global-set-key (kbd "C-/") 'yas-expand)
(find-file "~/tmp/test.org")

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)))

;; this allows tab - to expand yasnippet snippets that are elisp
(setq org-src-tab-acts-natively   t)
```

~/tmp/snippets/emacs-lisp-mode/+new-snippet+

``` # -*- mode: snippet -*-
 # name: def
 # key: def
 # --
(defun $1 ($2)
   (interactive)
   $0)
```
place cursor after def, in org file ~/tmp/test.org, and `yas-expand'
```
#+begin_src elisp :result output
   def
#+end_src
```
I get this error

```Error in post-command-hook 
(yas--post-command-handler): 
(wrong-number-of-arguments (lambda (regexp ws-count) 
"Move point to location saved by `yas--snapshot-marker-location'.
Buffer must be narrowed to BEG..END used to create the snapshot info." 
(goto-char (point-min))
 (if (not (looking-at regexp)) 
(lwarn (quote (yasnippet re-marker)) :warning "Couldn't find: %S" regexp) 
(goto-char (match-beginning 1)) 
(skip-chars-forward "[:space:]
") (skip-chars-backward "[:space:]
" (- (point) ws-count)))) 3)
```

M-x describe-variable post-command-hook

```
post-command-hook is a variable defined in ‘C source code’.
Its value is (t)
Local in buffer test.org; global value is 

(global-font-lock-mode-check-buffers
 global-eldoc-mode-check-buffers 
yas-global-mode-check-buffers)
```

I tried adding the following things but they made no difference.

`(setq org-src-fontify-natively t)`

`(setq org-edit-src-content-indentation 4)`

```
(defun my-org-mode-hook ()
  (setq-local yas-buffer-local-condition
              '(not (org-in-src-block-p t))))

(add-hook 'org-mode-hook #'my-org-mode-hook)
```

GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.24) of 2017-11-09
yasnippet - last commit  Date:   Mon Oct 15 08:12:51 2018 -0400
Org mode version 9.1.5 (release_9.1.5-275-g58c9be @ /usr/local/share/emacs/27.0.50/lisp/org/)

**Comment by npostavs** [comment] 2019-04-10 12:43
@dericbytes I'm having trouble replicating this error at the moment,
but I remember seeing something like it earlier.  I dug up some old
code which was my initial attempt at fixing it.  Can you try out the
patch in #989 to see if it helps?

**Comment by dericbytes** [comment] 2019-04-10 16:50
I tried it and can no longer expand emacs lisp snippets in an elisp source block.

I have yasnippet - dabc71992158b749f7b7e745908a51a7011a117d

rm yasnippet.elc
rm yasnippet.el
cp #989yasnippet.el $yas-source-dir

M-x byte-compile-file

M-x org-mode
M-x yas-new-snippet my-org-snippet
my-org-snippet works in and out of source block
M-x emacs-lisp-mode 
M-x yas-new-snippet my-elisp-snippet
M-x org-mode
my-elisp-snippet does not expand in elisp org source block.

**Comment by npostavs** [comment] 2019-04-10 17:04
> I tried it and can no longer expand emacs lisp snippets in an elisp source block.

Hmm, is this from `emacs -Q` or do you still have that advice you posted above active?

**Comment by dericbytes** [comment] 2019-04-10 17:13
I am using emacs -Q. It was because 

```
(setq org-src-tab-acts-natively t)
```
code was not run. Due to a new error

```
org-link-set-parameters: Symbol’s function definition is void: org-element-update-syntax
```

now it expands but I get the same error

```
Warning (yasnippet): Couldn’t find: "[[:space:]
]*\\(\\)[[:space:]
]*(defun[[:space:]
]*()"
Warning (yasnippet): Couldn’t find: "[[:space:]
]*)[[:space:]
]*\\(\\)"
```

**Comment by npostavs** [comment] 2019-04-10 17:38
> ~/tmp/snippets/emacs-lisp-mode/+new-snippet+

Argh, I got mixed up and was creating the new snippet in `org-mode`, that's why I couldn't reproduce anything. I can now see everything you've reported. Well, almost everything, I'm not seeing that `org-link-set-parameters: Symbol’s function definition is void: org-element-update-syntax` thing, but everything else, including the warning you posted after I do see.

For easier reference, I'm posting a quicker reproducer below (save to a file, e.g., `issue-976-org-src-expand.el`, and then run `emacs -Q -L dir/of/yasnippet -l issue-976-org-src-expand.el` and hit <kbd>TAB</kbd> after it finishes loading).

```elisp
;;; emacs -Q
(require 'yasnippet)
(yas-global-mode 1)

(require 'org)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)))

;; this allows tab - to expand yasnippet snippets that are elisp
(setq org-src-tab-acts-natively   t)

(yas-define-snippets
 'emacs-lisp-mode
 '(("def" "\
\(defun $1 ($2)
   (interactive)
   $0\)")))

(org-mode)
(insert "
#+begin_src elisp :result output
   def
#+end_src")

;;; Need to delay this, otherwise point is not set properly.
(run-at-time 0 nil
             (lambda ()
               (goto-char (point-min))
               (search-forward "def")))
```

**Comment by dericbytes** [comment] 2019-04-10 20:47
I ran that. I didn't get the `org-link-set-parameters` message but still got ` Couldn’t find: "[[:space:]` warning popup box.

**Comment by npostavs** [comment] 2019-04-10 22:12
>  I didn't get the `org-link-set-parameters` message but still got ` Couldn’t find: "[[:space:]` warning popup box.

Right, same here. Do you know what you did differently previously that you got the `org-link-set-parameters`  error?

Meanwhile, I pushed a fix for the `Couldn’t find: "[[:space:]...` failure to #989, please try it out.

**Comment by dericbytes** [comment] 2019-04-10 22:30
I can not reproduce the error `org-link-set-parameters`

Your fix works. Thanks.

(I had to manually surf the web and cut and paste your patches. What is a better way of doing this using emacs?)

**Comment by npostavs** [comment] 2019-04-10 23:26
> Your fix works. Thanks.

Great! Thanks for testing. I'll polish it up with some much needed comments/docstrings; I expect to push it sometime this weekend at the latest.

> (I had to manually surf the web and cut and paste your patches. What is a better way of doing this using emacs?)

There are a few options. Not sure what the best way is.  
- You could get the complete file here: https://raw.githubusercontent.com/npostavs/yasnippet/org-unbork/yasnippet.el.
- You can get it by pulling the `org-unbork` branch from my fork via git (https://github.com/npostavs/yasnippet.git).
- You can get it by pulling from this (joaotavora's) repo, by with `git fetch origin pull/989/head:BRANCHNAME` (see https://help.github.com/en/articles/checking-out-pull-requests-locally)
- You could try using [forge](https://github.com/magit/forge) which is an Emacs interface to Github, works as an addon to magit. I would say forge is still in "alpha", so expect some to encounter some bugs and unexpected behaviour if you try that route (also, it's probably overkill for just grabbing a single file from a single pull request).

**Closed** 2019-04-14 16:22 UTC
Labels: bug, integration
