### ISSUE TITLE
once snippet for c++ headers not working [Emacs 25.1.50]

### ISSUE THREAD

**Issue by jvillasante** [joaotavora/yasnippet#713] opened 2016-07-03 00:09 UTC
On a file called `Window.h` if I try to expand the `once` snippet here's what I get:

```
#ifndefWINDOW_H}
#define 



#endif /*  */
```

**Comment by npostavs** [comment] 2016-07-03 00:50
Um, works for me. Can you reproduce this from [`emacs -Q`][emacs-Q]?

Here is what I get
```
#ifndef WINDOW_H
#define WINDOW_H



#endif /* WINDOW_H */
```

[emacs-Q]: http://www.lunaryorn.com/2015/11/29/reproduce-bugs-in-emacs-Q.html

**Comment by cslux** [comment] 2016-07-07 18:15
Same result as @jvillasante got. Steps to reproduce.

1) Start emacs 
``` bash
    emacs -Q
```
2) Add yasnippet to load path
``` elisp
(add-to-list 'load-path (expand-file-name "~/.emacs.d/elpa/yasnippet-20160705.2039"))
```
3) Load yasnipppet and enable yasnippet globaly
``` elisp
(require 'yasnippet)
(yas-global-mode)
```
4) Open e.g.  `generator.cc` file, enter `once` and hit `TAB` 
``` cxx
#ifndefGENERATOR_H_}
#define 



#endif /*  */
```

regards
Christian

**Comment by npostavs** [comment] 2016-07-07 22:50
Hmm, I'm still not able reproduce it here. What do you get from
```elisp
(yas--template-content
 (cdar (mapcan #'(lambda (table)
                   (yas--fetch table "once"))
               (yas--get-snippet-tables 'c++-mode))))
```

**Comment by cslux** [comment] 2016-07-08 05:59
This:
``` 
"#ifndef ${1:_`(upcase (file-name-nondirectory (file-name-sans-extension (buffer-file-name))))`_H_}
#define $1

$0

#endif /* $1 */"
```

**Comment by cslux** [comment] 2016-07-08 06:29
Ahhh, that's weird, I don't know why but if nothing is above once (e.g. generator.cc) is empty or above `once` is the file header, like

``` cxx
// (c) Copyright ....
// Documentation
#include "hello_world.h"
once|
```

the result is
``` cxx
#ifndef GENERATOR_H_}
#define 

#endif /*  */
```

But if the file is like:
``` cxx
// (c) Copyright ....
// Documentation
#include "hello_world.h"

void hello_world() { }
once|
```

I get the correct result.
``` cxx
#ifndef _GENERATOR_H_
#define _GENERATOR_H_

#endif /* _GENERATOR_H_ */
```
`|` is the cursor

`emacs-version` 
GNU Emacs 25.1.50.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-07-03

**Comment by cslux** [comment] 2016-07-08 07:57
I tried it at work too! This version is not from HEAD but from the emacs-25 branch. Result, it works regardless of the file content.

`emacs-version`
GNU Emacs 25.0.94.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.4.2) of 2016-06-05

So must be, at least for me, some bug/changes in the Emacs core elisp packages I guess. @jvillasante What is your Emacs version? `M-x emacs-version RET`
 
@npostavs I will try to dick a bit deeper on the weekend maybe I find out whats wrong in Emacs 25.1.50.1.

**Comment by npostavs** [comment] 2016-07-08 11:06
> I tried it at work too! This version is not from HEAD but from the emacs-25 branch. Result, it works regardless of the file content.

Ah, ok, I see it with emacs-master too. So this may be an Emacs bug.

**Comment by xaxousis** [comment] 2016-08-29 14:57
A work around that works for me is to add a mirror that ignores the `yas-text` variable at the beginning of the snippet. Which give something like:
```
${1:$(ignore yas-text)}#ifndef ${1:HEADER_GUARD}
#define $1

$0

#endif /* $1 */
```

**Comment by npostavs** [comment] 2016-09-19 03:00
I can no longer reproduce this, perhaps it was fixed in Emacs?

**Comment by npostavs** [comment] 2016-10-04 01:59
> perhaps it was fixed in Emacs?

As there have been no reports to the contrary, I will assume yes.

**Closed by npostavs** 2016-10-04 01:59 UTC
Labels: emacs-bug
