### ISSUE TITLE
$1 eating whitespace

### ISSUE THREAD

**Issue by rthalley** [joaotavora/yasnippet#768] opened 2017-01-22 20:10 UTC
My emacs was build from the master branch this morning

```
  $ cd ~/src/emacs

  $ git log -1 --oneline
  0a49f158f1 Improve uses of CHECK_LIST etc.

  $ HOME=`pwd` /Applications/Emacs.app/Contents/MacOS/Emacs --version
  GNU Emacs 26.0.50.3
  Copyright (C) 2017 Free Software Foundation, Inc.
  GNU Emacs comes with ABSOLUTELY NO WARRANTY.
  You may redistribute copies of GNU Emacs
  under the terms of the GNU General Public License.
  For more information about these matters, see the file named COPYING.

  $ git clone https://github.com/joaotavora/yasnippet.git yasnippet-bug
  Cloning into 'yasnippet-bug'...
  remote: Counting objects: 8828, done.
  remote: Total 8828 (delta 0), reused 0 (delta 0), pack-reused 8828
  Receiving objects: 100% (8828/8828), 4.55 MiB | 935.00 KiB/s, done.
  Resolving deltas: 100% (3418/3418), done.

  $ cd yasnippet-bug/

  $ git log -1 --oneline
  48cd716 Use more compact format for snippet menus

  $ cd ..

  $ ls -R .emacs.d
  auto-save-list  init.el         snippets

  .emacs.d/auto-save-list:

  .emacs.d/snippets:
  c++-mode

  .emacs.d/snippets/c++-mode:
  gsf
```

There is no non-default config

```
  $ cat .emacs.d/init.el
```

Here is my template

```
  $ cat .emacs.d/snippets/c++-mode/gsf
  # -*- mode: snippet -*-
  # name: gsf
  # key: gsf
  # --
  ${1:type} ${2:name}() const { return $2_; }
  void set_$2($1 $2) { $2_ = $2; }
  $2 $1_;
  $2 $1 bar;
  $1 $2_;
  $1 $2 bar;
  $1 $1 $2_;
```

Run emacs

```
  $ HOME=`pwd` /Applications/Emacs.app/Contents/MacOS/Emacs -L yasnippet-bug
```

I now do M-: (require 'yasnippet) and and M-x yas-global-mode.  I open
an emtpy file, foo.cc, and type "gsf<tab>"

The snippet expands, but there is weird space-eating going on with tab stop
1.  It expands to:
```
  type name() const { return name_; }
  void set_name(type name) { name_ = name; }
  name type_;
  name type bar;
  typename_;
  typename bar;
  typetypename_;
```
Note that the space after $1 has been eaten consistently on the last 3
lines, but that it was NOT eaten on the fourth line from the top.  The
expansion I expected is:
```
  type name() const { return name_; }
  void set_name(type name) { name_ = name; }
  name type_;
  name type bar;
  type name_;
  type name bar;
  type type name_;
```
The last line of the expansion isn't meant to be valid C++, it's just
to illustrate that whitespace seems to be consistently eaten after $1.
Also note that "$2 $1_" doesn't have any trouble but "$1 $2_" does.

**Comment by npostavs** [comment] 2017-01-22 22:20
Thanks for the report, confirmed also with Emacs 25.1 on GNU/Linux, and tip of the not-yet-merged `filter-key` branch. Note that it doesn't happen when expanding the snippet inside braces (probably because the indentation is increased in that case).

This looks like a case that isn't covered by the marker restoration code in #755.

> Also note that "$2 $1_" doesn't have any trouble but "$1 $2_" does.

This points to a possible solution, it might just be matter of making sure we restore the markers in a certain order.

**Comment by npostavs** [comment] 2017-01-25 06:22
Ah, actually this is another case of #712, we do indentation before we fill in all the mirrors, so the whitespace can be killed. So either we have to more clever about the order we update in, or we switch to solution 3 mentioned in https://github.com/joaotavora/yasnippet/issues/712#issuecomment-228332470

**Comment by npostavs** [comment] 2017-01-28 05:32
Please try out #769.

**Comment by rthalley** [comment] 2017-01-28 13:13
That fixes it for me, thanks!

**Closed** 2017-01-31 13:56 UTC
Labels: bug
