### ISSUE TITLE
Is there a way to install yansippet from package.el without all the snippets?

### ISSUE THREAD

**Issue by computersarecool** [joaotavora/yasnippet#872] opened 2017-12-03 06:56 UTC
When I run `package-install` on Yas (on Emacs 24+) I get many many bundled snippets that I do not want.  Is it possible to install the mode without all the packaged snippets?

**Comment by npostavs** [comment] 2017-12-03 12:21
Duplicate of #775

**Comment by npostavs** [comment] 2017-12-03 12:22
It will be possible soon, see #858.

**Closed by npostavs** 2017-12-03 12:22 UTC

**Comment by computersarecool** [comment] 2017-12-03 14:08
Sorry for the duplicate. I remember asking this and couldn't find the issue. Happy to hear it is coming. Thanks for your work!
