### ISSUE TITLE
One test failure with Emacs 26 pretest

### ISSUE THREAD

**Issue by phst** [joaotavora/yasnippet#866] opened 2017-10-31 23:09 UTC
When running `rake tests` using an Emacs binary built from the `emacs-26` release branch, I get one test failure:

```
Test yas-org-native-tab-in-source-block backtrace:
  signal(ert-test-failed (((should (looking-at ">> done!")) :form (loo
  ert-fail(((should (looking-at ">> done!")) :form (looking-at ">> don
  (if (unwind-protect (setq value-706 (apply fn-704 args-705)) (setq f
  (let (form-description-708) (if (unwind-protect (setq value-706 (app
  (let ((value-706 'ert-form-evaluation-aborted-707)) (let (form-descr
  (let* ((fn-704 (function looking-at)) (args-705 (condition-case err 
  (progn (require 'font-lock) (font-lock-mode 1) (org-mode) (yas-minor
  (unwind-protect (progn (require 'font-lock) (font-lock-mode 1) (org-
  (let ((noninteractive nil) (change-major-mode-after-body-hook (funct
  (save-current-buffer (set-buffer temp-buffer) (let ((noninteractive 
  (let ((temp-buffer (generate-new-buffer "*yas-temp*"))) (save-curren
  (let ((text-mode-hook '(yas-minor-mode)) (org-src-tab-acts-natively 
  (closure (yas--another-test-mode-abbrev-table yas--another-test-mode
  funcall((closure (yas--another-test-mode-abbrev-table yas--another-t
  (progn (mapc (function yas-make-file-or-dirs) dirs) (funcall fn))
  (unwind-protect (progn (mapc (function yas-make-file-or-dirs) dirs) 
  (progn (if with-temp-message (progn (setq current-message (current-m
  (unwind-protect (progn (if with-temp-message (progn (setq current-me
  (let ((with-temp-message "") (current-message)) (unwind-protect (pro
  (let* ((default-directory (make-temp-file "yasnippet-fixture" t)) (y
  yas-call-with-snippet-dirs(((".emacs.d/snippets" ("text-mode" ("T" .
  (closure (yas--another-test-mode-abbrev-table yas--another-test-mode
  funcall((closure (yas--another-test-mode-abbrev-table yas--another-t
  (unwind-protect (funcall fn) (let* ((--cl-var-- vars) (var nil) (--c
  (let* ((vars (yas-variables)) (saved-values (mapcar (function symbol
  yas-call-with-saving-variables((closure (yas--another-test-mode-abbr
  (closure (yas--another-test-mode-abbrev-table yas--another-test-mode
  ert--run-test-internal(#s(ert--test-execution-info :test #s(ert-test
  ert-run-test(#s(ert-test :name yas-org-native-tab-in-source-block :d
  ert-run-or-rerun-test(#s(ert--stats :selector t :tests [#s(ert-test 
  ert-run-tests(t #f(compiled-function (event-type &rest event-args) #
  ert-run-tests-batch(nil)
  ert-run-tests-batch-and-exit()
  command-line-1(("-L" "." "-l" "yasnippet-tests.el" "-f" "ert-run-tes
  command-line()
  normal-top-level()
Test yas-org-native-tab-in-source-block condition:
    (ert-test-failed
     ((should
       (looking-at ">> done!"))
      :form
      (looking-at ">> done!")
      :value nil))
   FAILED  69/69  yas-org-native-tab-in-source-block

Ran 69 tests, 68 results as expected, 1 unexpected (2017-11-01 00:05:38+0100)
2 expected failures

1 unexpected results:
   FAILED  yas-org-native-tab-in-source-block

rake aborted!
```

This is at YASnippet repository version 35a4df769cbdebd10d043f16d680bdb16ee858ed and Emacs repository version 460fe4a1bc40f2ba39deda6448a7baf57e0e6b76.

**Comment by npostavs** [comment] 2017-10-31 23:18
Yeah, this is duplicate of #852, should have marked this as expected to fail.

**Closed** 2017-10-31 23:18 UTC
Labels: duplicate
