### ISSUE TITLE
How to override snippets inherited from parents?

### ISSUE THREAD

**Issue by kshenoy** [joaotavora/yasnippet#917] opened 2018-03-13 02:28 UTC
Hi, I found this mentioned in passing in [Organizing snippets](http://joaotavora.github.io/yasnippet/snippet-organization.html#sec-2) but it only covers the case when multiple sources are set up and not when inheriting from parent modes.

I'm trying to do the following. In cc-mode, I want to define an enum snippet like this:

    enum ${1:name} { $0 };

while in c++-mode, I want to use this definition:

    enum class ${1:name} { $0 };

Hence, I created two files both called `enum`, both having the same key and placed one in the cc-mode directory and one in c++-mode. In c++-mode, I also created a .yas-parents file to inherit snippets from cc-mode. However, when I type `en TAB`, I get an option to select between the two enums instead of the latter overriding the former and presenting me with only one option (and hence, have it to expand automatically).

I tried to use `uuid` as described [here](https://joaotavora.github.io/yasnippet/snippet-development.html#sec-2-8). When I do this, it still shows two options. However, now both options expand to the C++ style enum.

What am I missing here? What's the right way to override snippets?

**Comment by npostavs** [comment] 2018-03-13 13:13
Duplicate of #270

**Closed by npostavs** 2018-03-13 13:13 UTC

**Comment by npostavs** [comment] 2018-03-13 13:14
You could probably work around it by adding a condition to the cc-mode snippet to prevent it from activating in c++-mode.
